---
title: "R Notebook"
output: html_notebook
---
```{r}
library(dplyr)
library(readr)
library(arrow)
library(lubridate)
```

```{r}
# Read the static house data from the 'static_house_data.csv' file
static_house_data <- read.csv("static_house_data.csv")
```

```{r}
# Read the weather data from the 'weather_data.csv' file
weather_data <-read.csv("weather_data.csv")
```

```{r}
# Read the energy usage data from the 'energy_usage_data.csv' file
energy_usage_data <- read.csv("energy_usage_data.csv")
```

```{r}
# Merge energy_data and static_house_data based on 'bldg_id'
energy_static_data <- merge(energy_usage_data, static_house_data, by = "bldg_id")
```

```{r}
energy_static_data$time <- as.POSIXct(energy_static_data$time)
```

```{r}
# Print or view the merged dataframe
energy_static_data

```
```{r}
# Convert 'time' column to POSIXct format
weather_data$time <- as.POSIXct(weather_data$time)
weather_data
```

```{r}
# Assuming 'time' is the POSIXct column in 'weather_data'
weather_data_aggregated <- weather_data %>%
  group_by(in.county, date = as.Date(time)) %>%
  summarise_all(mean, na.rm = TRUE)

# Viewing the first few rows of the aggregated dataset
weather_data_aggregated



```
```{r}
str(weather_data)
```


```{r}
energy_static_weather_data <- merge(energy_static_data, weather_data_aggregated, by = c("in.county", "time"))
```

```{r}
# Assuming energy_static_weather_data is your dataframe
energy_static_weather_data <- energy_static_weather_data[!apply(energy_static_weather_data == "None", 1, any), ]

```

```{r}
# Print or view the merged dataframe
energy_static_weather_data
```

```{r}
energy_static_weather_data
```

```{r}
write_csv(energy_static_weather_data, "/Users/vrushalilad/Desktop/IDS Project/energy_static_weather_data.csv")
```






